### ISSUE TITLE
::begin() always return true

### ISSUE THREAD

**Issue by av1024** [adafruit/RTClib#64]
There is no way to check if RTC chip is not available because `begin ()` simply returns `true`.

On my sensor board I use workaround for DS3231 but similar code should work on other IC:

``` c
bool RTC_DS3231::begin(void) {
  Wire.begin();
  uint8_t x = read_i2c_register(DS3231_ADDRESS, 6); // 0x00..0x99 - Year in BCD
  return x != 0xFF; // got 0xFF if chip not present
}
```

**Comment by gutierrezps** [comment]
I agree. I was facing issues with bad wire hookup on my protoboard, and I only knew the RTC wasn't properly connected because rtc.now() returned a weird date, like "2165/165/165".

Other approach would be to check if endTransmission() == 3 (Addr NACK) for a dummy byte, as stated in [Wire reference](https://www.arduino.cc/en/Reference/WireEndTransmission)

Talking about the RTC_XXX::begin() member, I would remove Wire.begin() from it, since I'm using ESP8266, and I could assign other pins than the defaults to I2C.

**Comment by av1024** [comment]
@gutierrezps +1!

I also use this lib with ESP8266, but with "standard" I2C pins so calling Wire.begin() does not matter. Also (at least at esp8266 library 2.1.0) You may call `Wire.begin(sda, scl) once in your code and pin assignments will preserved in next `.begin()` calls.

About endTransmission(): I'm not sure about valid result codes in esp8266 implementation (looks like `twi_writeTo` returns 3 as NACK on transmit data and 2 as NACK address). 

PS: Got "Bad gateway" on Wire reference url :(

**Comment by bhelterline** [comment]
+1 I modified my version to watch the result of endTransmission() and added a write in begin() so it actually returns false when there is no RTC.

```
boolean RTC_DS1307::begin(void) {
  Wire.begin();
  Wire.beginTransmission(DS1307_ADDRESS);
  Wire._I2C_WRITE((byte)0);
  if ( Wire.endTransmission() == 0 ) {
  return true;  
  }
  return false;
}

```

**Comment by ortegafernando** [comment]
Hi, is there any plan to include this in the master brand of the library ???? Thanks

**Comment by mouridis** [comment]
I submitted a PR for this issue guys but it only covers DS3231 which I have and I am able to confirm that the fix works without issues under AVR, ESP8266 and ESP32. Hopefully, it will be merged.
